package(default_visibility = ["//visibility:public"])

test_suite(
    name = "unit",
    tests = [
        "//crates/client-sdk:unit_test",
        "//crates/common:unit_test",
        "//crates/desktop-status:unit_test",
        "//crates/rendezvous-server:unit_test",
        "//crates/sync-core:unit_test",
        "//crates/transport-sdk:unit_test",
    ],
)
