load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

# This standalone service has only third-party dependencies, all of which are
# derived from Cargo.toml by Crate Universe.
rust_library(
    name = "stats_collector_server",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_name = "stats_collector_server",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    visibility = ["//crates:__subpackages__"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "unit_test",
    size = "small",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    crate = ":stats_collector_server",
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
)
