[package]
name = "common"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
quick-xml.workspace = true
serde.workspace = true
time = { version = "0.3", features = ["formatting"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unicode-general-category.workspace = true
uuid.workspace = true

[lints]
workspace = true
